const CommunityDb = [
  {
    name: "Music",
    about: "Let the Music do the talk",
    image: "url",
    slug: "music-community",
    members: [],
    numberOfMembers: 60,
    discussionTopic: [],
    comments: [],
  },
  {
    name: "Fine Art",
    about: "Yes is fine, this is the Art",
    image: "url",
    slug: "fine-art-community",
    members: [],
    numberOfMembers: 40,
    discussionTopic: [],
    comments: [],
  },
  {
    name: "Digital Art",
    about: "Dream in Digital",
    image: "url",
    slug: "digital-art-community",
    members: [],
    numberOfMembers: 50,
    discussionTopic: [],
    comments: [],
  },
  {
    name: "Writing & Poetry",
    about: "Tell me a story that rhymes",
    image: "url",
    slug: "writing-poetry-community",
    members: [],
    numberOfMembers: 80,
    discussionTopic: [],
    comments: [],
  },
  {
    name: "Photography",
    about: "Take a snapshot of a moment",
    image: "url",
    slug: "photography-community",
    members: [],
    numberOfMembers: 100,
    discussionTopic: [],
    comments: [],
  },
];

module.exports = CommunityDb;
